spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

